-   id: qs-cfn-lint
    name: AWS Quick Start Linter
    entry: cfn-lint
    language: python
    files: \.(json|yaml|yml)$
-   id: qs-cfn-lint-wrapped
    name: AWS Quick Start Linter
    entry: wrapped-cfn-lint
    language: python
    files: \.(json|yaml|yml)$
